### ISSUE TITLE
The form data request does not add an authorization token

### ISSUE THREAD

**Issue by TomasVrbkaBlogic** [gaboe/rest2ts#108] opened 2024-08-09 04:39 UTC
When the form data request is used, the updateHeaders function, which adds the Authorization token to the request, is not called. The updateHeaders function should also be called in this case.
![updateheaders](https://github.com/user-attachments/assets/9da8d6b7-8b5d-4b1b-a742-0e4d6d8e8cac)
Version 5.2.2.

**Comment by gaboe** [comment] 2024-08-09 04:59
@dejvidecz Is this intended behavior or a bug? It should call and updateHeaders and then remove Content-Type header, or append authorization only.

**Comment by dejvidecz** [comment] 2024-08-09 07:33
@gaboe 
It is a bug. 
Best way will be call updateHeaders and than remove Content-Type header.

**Comment by gaboe** [comment] 2024-08-09 17:58
Thanks for fixing Tomáš

https://github.com/gaboe/rest2ts/pull/109

Released in v5.2.7

**Closed** 2024-08-09 17:58 UTC
